server:
  port: 10001

spring:
  cloud:
    stream:
      # 消息源topic  注意source与 三种函数方法不兼容，如果定义了任意一个 function supplier 或者consumer 那么source将失效
      source: articlePublished
      bindings:
        articlePublished-out-0:
          destination: articlePublished


  datasource:
    # 动态数据源
    dynamic:
      primary: master
      strict: false
      datasource:
        # 真实来源
        master:
          url: jdbc:mysql://127.0.0.1:3306/article_source?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver

        # 本地存储
#        slave_1:
#          url: jdbc:mysql://127.0.0.1:3306/lucky_auth_localstory?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
#          username: root
#          password: root
#          driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    use-generated-keys: true
# 日志
logging:
  level:
    article: debug
    org.springframework: info